---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockoon-inventory
  namespace: central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockoon-inventory
  template:
    metadata:
      labels:
        app: mockoon-inventory
    spec:
      containers:
        - name: mockoon-inventory
          image: mockoon/cli:latest
          args: ["-d", "https://raw.githubusercontent.com/hugomcruz/files/main/inventory-mock.json"]
          ports:
            - containerPort: 3003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mockoon-inventory
  namespace: central
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP
  selector:
    app: mockoon-inventory
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mockoon-inventory
  namespace: central
spec:
  tls:
  - hosts:
    - mockoon.central.border.berzuk.com
  ingressClassName: nginx
  rules:
  - host: mockoon.central.border.berzuk.com
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mockoon-inventory
                port:
                  number: 80